<a href="https://colab.research.google.com/github/Addy0606/PytorchTutorial/blob/main/torchtutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.8.0+cu126


In [ ]:
## pytorch tensors created using torch.tensor
scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2328, 0.4683, 0.4818, 0.8027],
        [0.7203, 0.2505, 0.6979, 0.1171],
        [0.9632, 0.9385, 0.3414, 0.9244]])

In [ ]:
## random tensor similar to image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height width color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
##tensor of all zeroes

In [ ]:
zeroes= torch.zeros(3,4)
zeroes
##all ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
one_to_ten =torch.arange(0,10)
one_to_ten
## start=? end= ? step = ?

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0],dtype=None,device=None,requires_grad=False)
float_32_tensor

tensor([3.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.], dtype=torch.float16)

In [ ]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [ ]:
tensor=tensor-tensor
tensor

tensor([0, 0, 0])

In [ ]:
tensor=tensor+5
tensor


tensor([5, 5, 5])

In [ ]:
print(torch.mul(tensor,tensor))


tensor([25, 25, 25])


In [ ]:
print(f"{tensor*tensor}")

tensor([25, 25, 25])


In [ ]:
torch.matmul(tensor,tensor)


tensor(75)

In [ ]:
tensor @ tensor ## matrix mul
## inner dimensions must match
## result has shape of outer dims

tensor(75)

In [ ]:
#shapes for matrix mul

In [ ]:
tensor_a=torch.tensor([[1,2],[3,4],[5,6]])
tensor_b=torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_a,tensor_b) ## same as torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
## to fix tensor shape issues, manipulate shape of one tenesor using transpose

In [ ]:
## transpose fixes axes of one tensor

In [ ]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensor_a,tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
x = torch.arange(0,100,10)

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
## datatype is int64 or torch.long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [ ]:
x.argmin() ## position of min and max

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
## resjape: reshaps an input tensor to a defined shape

In [ ]:
##view: return a view of an input tensor of certain shape but keep the same memory as the original tensor
# stacking  : combine multiple tenmsors on top of each other (vstack) or side by side (hstack)
# squeeze- removes all 1 dimensions from a tensor
##unsqueeze - add a 1 dimension to a target tensor
# permute - return a view of the input wiht dimensions permuted (swapped) ina  certain way